import json
import os
import sys

# Flush output
sys.stdout.reconfigure(encoding='utf-8')

CITY_MAPPINGS = {
    'ahmedabad': ['Gujarat Metro', 'Ahmedabad'],
    'bengaluru': ['Namma Metro', 'Bangalore Metro'],
    'chennai': ['Chennai Metro'],
    'delhi_ncr': ['Delhi Metro', 'Noida Metro', 'National Capital Region Transport Corporation', 'NR', 'Rapid Metro Gurgaon'],
    'gurgaon': ['Rapid Metro Gurgaon'],
    'hyderabad': ['Hyderabad Metro'],
    'jaipur': ['Jaipur Metro'],
    'kochi': ['Kochi Metro'],
    'kolkata': ['Kolkata Metro'],
    'lucknow': ['Lucknow Metro'],
    'mumbai': ['Mumbai Metro', 'MMRDA', 'Mumbai Metro One'],
    'nagpur': ['Nagpur Metro', 'MahaMetro'],
    'navi_mumbai': ['Navi Mumbai Metro', 'CIDCO'],
    'pune': ['Pune Metro'],
    'kanpur': ['Kanpur Metro', 'Uttar Pradesh Metro Rail Corporation'],
    'agra': ['Agra Metro'],
    'indore': ['Indore Metro', 'Madhya Pradesh Metro Rail Corporation'],
    'bhopal': ['Bhopal Metro'],
}

def extract_all():
    print("Loading OSM Data...", flush=True)
    try:
        with open('assets/india_metro/india_metro_osm_stations.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
    except FileNotFoundError:
        print("Error: OSM data file not found.")
        return

    # Prepare containers
    city_stops = {city: [] for city in CITY_MAPPINGS}
    
    print(f"Processing {len(data)} items...", flush=True)
    
    count_kanpur = 0
    count_added = 0

    for item in data:
        network = str(item.get('network', ''))
        operator = str(item.get('operator', ''))
        name = item.get('name')
        if name is None: name = ''
        name = str(name)
        
        tags = item.get('tags')
        if tags is None: tags = ''
        tags = str(tags)
        
        # Combined search string
        combined_tag = (network + " " + operator + " " + name + " " + tags).lower()

        # Find matching city
        matched_city = None
        for city, keywords in CITY_MAPPINGS.items():
            for kw in keywords:
                if kw.lower() in combined_tag:
                    matched_city = city
                    break
            if matched_city:
                break
        
        if matched_city:
            stop_id = str(item.get('osm', {}).get('id', ''))
            # Use name from item or tags if missing
            if not name:
                name = item.get('tags', {}).get('name', 'Unknown')
                
            lat = item.get('lat')
            lng = item.get('lng')

            if lat and lng:
                stop_obj = {
                    "id": f"OSM_{stop_id}",
                    "name": name,
                    "lat": lat,
                    "lng": lng
                }
                city_stops[matched_city].append(stop_obj)
                count_added += 1
                
                if matched_city == 'kanpur':
                    count_kanpur += 1
            else:
                pass 

    print(f"Total processed: {count_added}. Kanpur found: {count_kanpur}", flush=True)

    # 1. Overwrite stops.json for each city (Optional for this task but good practice)
    # Skipping to focus on Dart file generation
    
    # 2. Generate Dart file for Dashboard
    dart_content = """// GENERATED FILE - DO NOT EDIT
// Source: india_metro_osm_stations.json
// Generated by: extract_all_stops.py

final List<Map<String, dynamic>> allIndiaStops = [
"""
    
    # Sort cities alphabetically
    sorted_cities = sorted(city_stops.keys())
    
    for city in sorted_cities:
        stops = city_stops[city]
        if not stops: 
            continue
            
        dart_content += f"  // --- {city.replace('_', ' ').title()} ---\n"
        
        # Sort stops by name within city
        sorted_stops = sorted(stops, key=lambda x: x['name'])
        
        for stop in sorted_stops:
            dart_content += f"""  {{
    "id": "{stop['id']}",
    "name": "{stop['name'].replace('"', '\\"')}",
    "lat": {stop['lat']},
    "lng": {stop['lng']},
  }},
"""

    dart_content += "];\n"

    dart_path = 'lib/all_india_stops.dart'
    with open(dart_path, 'w', encoding='utf-8') as f:
        f.write(dart_content)
    
    print(f"Generated {dart_path} with {sum(len(s) for s in city_stops.values())} total stops.", flush=True)

if __name__ == "__main__":
    extract_all()
